apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-app-service
spec:
  selector:
    app: my-fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080  # You can choose any port in the range 30000-32767
  type: NodePort